### ISSUE TITLE
Incompatible with grafana_ynh 

### ISSUE THREAD

**Issue by arthurlutz** [YunoHost-Apps/scrutiny_ynh#13]
### Describe the bug

When scrutiny is installed, you can't install grafana. (Haven't tried the other way round) 

### Context

- Hardware: *Old computer*
- YunoHost version: 11.2.5 (stable).
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: various install tweaks

### Steps to reproduce

- Install scrutiny
- Try to install grafana

### Expected behavior

To have both applications running side-by-side

### Logs

See https://github.com/YunoHost-Apps/grafana_ynh/issues/122

**Comment by ewilly** [comment]
yes known incompatibility : Scrutiny needs influxdb > v2.2 when graphana doesn't and use the debian version which is v1 only. Can't do anything about that in scrutiny packaging.
